### ISSUE TITLE
Option to dismiss on focus lost

### ISSUE THREAD

**Issue by robert-sandor** [sonnyp/Junction#10]
Add an option to dismiss the app on focus lost.
This would be much easier for a mouse user, than dismissing with Esc in case of a mis-click.
At the moment, losing focus just hides the window behing others, and leaves it open.

**Comment by sonnyp** [comment]
A close button is a better solution.

* Loosing focus by mistake is too easy.
* Junction may also loose focus because you want to check something first by alt-tabbing.
* Or something unexpectedly grabs the focus.

**Comment by sonnyp** [comment]
I have been thinking of making Junction keeping the history of requested locations, in which case I would be open to this being default since closing by accident could be recovered.

I had a look how to do this out of curiosity and unless I'm missing something, it is rather tricky

```js
  window.connect("notify::is-active", () => {
    if (window.is_active) {
      window.close();
    }
  });
```

On GNOME Shell / wayland ; the window closes when

* moving it
* when opening the application menu
* when opening the window menu (right click on header bar)
* when opening the entry menu (right click on the resource location)

there is also no way to skip the task bar on GTK4 or Wayland so AFAIK Junction will never really feel like a modal.

There are probably ways to workaround these but unless we want close on blur as standard behavior I don't think it's worth it.

**Comment by defini-tiv** [comment]
sad.
I think it would be the most intuitive option since e.g. the android dialogues behave the same.
It is definetly a flaw of gtk4 (or wayland) that such a usecase is not thought of.
So there should be comunicated somehow i guess...
