### ISSUE TITLE
Circular or Grid app icon layout

### ISSUE THREAD

**Issue by adrinux** [sonnyp/Junction#30]
Is it possible to have an optional circular or grid arrangement of application icons instead of a single long line?
I maybe something of an edge case but it gets awkward with a lot of browsers installed.

![junction](https://user-images.githubusercontent.com/41276/143321186-e0dd710c-a391-4d24-b6ee-2933937ce751.png)

**Comment by rohmishra** [comment]
Woah that's a lot of browsers mate you just woke up and decided to install ALL the browser!

A grid solution may be preferable. Circular arrangement seems to complicated to understand and may require a rewowrk of entire UI. For grid, we may want to break of to new line after every four or five icon, and align them to center so that if a row is not filled, they have equal spacing on both sides.

**Comment by sonnyp** [comment]
Grid is the way to go.

Icons should align left/start so you know which one you'll select if you press the down arrow - like the app grid in GNOME Shell.

It should be fairly easy to do and a great introduction to GTK. @rohmishra would you like to give it a try?

**Comment by rohmishra** [comment]
It might take me some time to get it done cause I don't really get much time to do anything outside of work these days but I'd certainly give it a shot over weekends if nobody else does it first :P

**Comment by sonnyp** [comment]
What about using the same solution than #31 #32 for this - at least for now

![Screenshot from 2021-12-01 20-17-58](https://user-images.githubusercontent.com/19673/144299608-7c0f7426-98de-41fc-9a27-fd0eaaf6a601.png)

![Screenshot from 2021-12-01 20-18-23](https://user-images.githubusercontent.com/19673/144299606-ad3b7dd7-e156-4741-86b3-8407ec6d23cb.png)

We could show 5 most recent used apps only (+ the ... icon) and the rest is accessible via the modal.

**Comment by sonnyp** [comment]
I have limited the number of options to 4 applications + the "View All" button for now (see above screenshot)

I will leave this open for now but I think there might be many options worth considering - specially since I'd like to support mobile

* Grid
* Horizontal scroll
* Vertical layout https://github.com/sonnyp/Junction/issues/18#issuecomment-954121822
* Search as you type

@adrinux in the meantime - can you tell us more about the use case for having so many browsers and for displaying them all in Junction ?

**Comment by adrinux** [comment]
> can you tell us more about the use case for having so many browsers and for displaying them all in Junction ?

In part it's for front end web dev and browser testing. In part because I tend to compartmentalize different tasks/projects in different browsers.

Why do I need them all in Junction? I don't, but I have them installed and Junction found them all - there doesn't seem to be a way to exclude any at present? Currently running Junction 1.2 on manjaro Gnome.

I switched from OSX in 2017 so memory may be getting rusty but I used [Choosy](https://www.choosyosx.com/help/settings/prompt) which has both a circular arrangement option and the ability to only show some browsers.

So yes, while I'd prefer a default of 5 or 6 apps to 4, the ability to limit which apps are shown would be helpful and in this case make the need for a more compact layout moot.

The suggestion of a grid or circular layout was more about reducing the mousing distance.

**Comment by rohmishra** [comment]
Yeah this might make sense but it really depends on how many of the app options users use on their systems regularly. We might wanna get some more feedback from people on what works. Specifically: would this add more friction compared to a grid/scrollable list and how many options do we wanna show by default?

**Comment by adrinux** [comment]
> And i get the web dev use case. I too have six browsers installed and cycle through them regularly enough for testing that having them shunted off to a different menu might end up being a bit more clunky.

Yep. Personally the dev/beta browsers are in my Gnome dash and I'm happy to access them from there. I won't usually be opening clicked links in them, they don't need to be in Junction.

I view Junction as being more useful in day to day browsing - click a link in an email and open it in X browser. Actually I'd probably only use  Firefox/Vivaldi/Opera/Chromium that way. Maybe 4 is enough :)

ps @rohmishra
> mate you just woke up and decided to install ALL the browser!
Hardly, I mean I could also install Falkon, Midori, Epiphany, LibreWolf and more... Junction doesn't even list Tor =D

**Comment by sonnyp** [comment]
Personally for web dev / testing - I use Junction ctrl+Click feature to quickly open a link in multiple browsers but I usually only test in Firefox, Epiphany and Chromium. Not sure it's helpful to test in more Blink based browsers as they all render the same so I'm hoping 4 is enough for now even for that use case.

> Junction doesn't even list Tor =D

Please report the issue to your packager https://github.com/sonnyp/Junction/issues/8

**Comment by gitSaptarshi** [comment]
How about a scrollable list? By default only show most used / recently used 4 options and then scroll to show more options. Also adding an option to drag n drop rearranging (though this will make it more complicated).

**Comment by rohmishra** [comment]
This does look like a better option but maybe we might wanna list 5-6 apps instead? That still wouldn't be too big but might be more convenient?

**Comment by rohmishra** [comment]
I now locally have a branch for a grid as well, this should no longer be a issue since Junction is already limiting apps to four at a time. Do we wanna keep the current behaviour or do we want to let the user decide using a toggle? 

What do you think Sonny? Personally I think limiting the options might be a better option anyways, esp if we land something to solve #29 or at least list the most commonly used app.

**Comment by sonnyp** [comment]
> How about a scrollable list?

https://github.com/sonnyp/Junction/issues/30#issuecomment-984038807 

> What do you think Sonny?

I think it's a bit too early in the project to decide and this requires more thoughts .

There is also overlap with https://github.com/sonnyp/Junction/issues/12 and potential new features such as search as you type or support for desktop file actions . But specifically, both the order and the layout will have to be decided together to make sense.

Let's think about this and revisit it in the future.

Agree that https://github.com/sonnyp/Junction/issues/29 makes sense regardless.
